### ISSUE TITLE
似乎与最新版本的某个库不兼容

### ISSUE THREAD

**Issue by qouteall** [gavinliu6/vuepress-theme-mix#11]
一开始我的package.json是这样的
```
{
  "devDependencies": {
    "vuepress": "^2.0.0-beta.43",
    "vuepress-theme-mix": "^1.3.2"
  }
}
```
然后一旦使用`mixTheme`后页面不显示，浏览器中出现了这个错误
```
Uncaught (in promise) Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (chunk-RTLFYRTT.js:35:11)
    at setup (Layout.vue:57:25)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5660:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
```

然后把package.json中改为`"vuepress": "2.0.0-beta.43",`然后就正常了。似乎与某个库的最新版本不兼容？

**Comment by qouteall** [comment]
发现重复的issue https://github.com/gavinliu6/vuepress-theme-mix/issues/10
但我用的是1.3.2仍然有这个问题

**Comment by gavinliu6** [comment]
请问出现错误的时候，你的 vuepress 确切版本是？

**Comment by qouteall** [comment]
我重新测试了一下，都锁最新版能复现问题
package.json
```
{
  "name": "test-mix",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "vuepress": "2.0.0-beta.48",
    "vuepress-theme-mix": "1.3.2"
  },
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  }
}
```
yarn.lock
[yarn.lock.txt](https://github.com/gavinliu6/vuepress-theme-mix/files/8896207/yarn.lock.txt)

**Comment by ten-ltw** [comment]
@gavinliu6 目前兼容版本是多少，是否可以在 release 时注明当时的适配版本。

**Comment by gavinliu6** [comment]
目前兼容 `2.0.0-beta.43`，以后我会在文档中说明兼容的 VuePress 版本号。

**Comment by gavinliu6** [comment]
已经兼容 VuePress v2.0.0-beta.48
